# Generated by Django 5.0.6 on 2025-10-31 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminanalytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='user_agent',
            field=models.TextField(blank=True),
        ),
    ]
