# Generated by Django 5.0.6 on 2025-10-31 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminanalytics', '0002_gamesession_user_agent'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='gamesession',
            index=models.Index(fields=['started_at'], name='adminanalyt_started_ba9d91_idx'),
        ),
        migrations.AddIndex(
            model_name='gamesession',
            index=models.Index(fields=['ended_at'], name='adminanalyt_ended_a_c6f00d_idx'),
        ),
        migrations.AddIndex(
            model_name='gamesession',
            index=models.Index(fields=['score'], name='adminanalyt_score_507868_idx'),
        ),
    ]
