# Generated by Django 5.0.6 on 2025-10-31 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminanalytics', '0003_gamesession_adminanalyt_started_ba9d91_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='gamesession',
            index=models.Index(fields=['client_tag'], name='adminanalyt_client__8cf9d8_idx'),
        ),
    ]
